### ISSUE TITLE
I ran the test example using ESP3 WROOM 32 and encountered an error

### ISSUE THREAD

**Issue by 90757665** [pschatzmann/arduino-freertos-addons#2]
`#include "freertos-all.h"

Queue queue(100, sizeof(size_t));
Task task("name",1000,10, [](){ static size_t count=0; queue.Enqueue(&(++count));});

void setup() {
  Serial.begin(115200);
  task.Start(0);
}

void loop() {
  size_t result;
  queue.Dequeue(&result);
  Serial.println(result);
}`

error message：

In file included from g:\Arduino IDE\libraries\freertos-addons\src/task.hpp:4:0,
                 from g:\Arduino IDE\libraries\freertos-addons\src/freertos-all.h:7,
                 from C:\Users\Administrator\AppData\Local\Temp\.arduinoIDE-unsaved2023510-6320-ip9yv.qs0qqi\sketch_jun10b\sketch_jun10b.ino:1:
g:\Arduino IDE\libraries\freertos-addons\src/thread.hpp: In member function 'char* cpp_freertos::Thread::GetName()':
g:\Arduino IDE\libraries\freertos-addons\src/thread.hpp:268:40: error: 'pcTaskGetName' was not declared in this scope
             return pcTaskGetName(handle);
                                        ^
In file included from g:\Arduino IDE\libraries\freertos-addons\src/freertos-all.h:18:0,
                 from C:\Users\Administrator\AppData\Local\Temp\.arduinoIDE-unsaved2023510-6320-ip9yv.qs0qqi\sketch_jun10b\sketch_jun10b.ino:1:
g:\Arduino IDE\libraries\freertos-addons\src/critical.hpp: In static member function 'static BaseType_t cpp_freertos::CriticalSection::EnterFromISR()':
g:\Arduino IDE\libraries\freertos-addons\src/critical.hpp:94:48: error: 'taskENTER_CRITICAL_FROM_ISR' was not declared in this scope
             return taskENTER_CRITICAL_FROM_ISR();
                                                ^
g:\Arduino IDE\libraries\freertos-addons\src/critical.hpp: In static member function 'static void cpp_freertos::CriticalSection::ExitFromISR(BaseType_t)':
g:\Arduino IDE\libraries\freertos-addons\src/critical.hpp:108:60: error: 'taskEXIT_CRITICAL_FROM_ISR' was not declared in this scope
             taskEXIT_CRITICAL_FROM_ISR(savedInterruptStatus);
                                                            ^

exit status 1

Compilation error: exit status 1

**Comment by pschatzmann** [comment]
I can't reproduce your issue and the code that you posted above does not correspond to my example at all! You are supposed to pass a method or a lambda function as argument!

Also make sure  that you use an actual version of the Arduino ESP32 core. 1.0.6 is obsolete for more than 2 years now! The actual version is 2.0.9!
